#!/usr/bin/env python3
# /// script
# dependencies = ["fastapi", "uvicorn"]
# ///
"""Serve the study shelf with a guide chat panel.

Binds 127.0.0.1 only. On startup the shelf page is regenerated by importing
the sibling build_shelf.py by path (importlib, the same pattern the tests
use) rather than shelling out through `uv run` — build_shelf is stdlib-only,
so importing it is fast, in-process, and fails loudly if it breaks.

Routes:
    GET  /          the shelf page (library/shelf.html, freshly rebuilt)
    GET  /health    {"ok": true, "brain": <default>, "brains": {name: available}}
    POST /api/chat  {"messages": [...], "brain"?, "session"?, "view"?} ->
                    streamed reply. "brain" is optional and per-request (the
                    panel's toggle); it falls back to the server's --brain
                    default, unknown names are a 400. "session" picks the
                    conversation ("new" starts fresh — new claude thread
                    too; default: the current/most-recent one). "view" is
                    the talk slug open on the shelf, or null — it becomes
                    ambient context (see below). The X-Session response
                    header names the session that recorded the turn.
    GET  /api/sessions  {"sessions": [{id,title,summary,updated}...]}, newest
                    first, for the sidebar's Sessions list.
    GET  /api/history?session=<id>  that session's last 50 completed turns
                    (default: the current/most-recent session) plus its id.
    /<talk>/...     library/ served statically (Range supported, audio seeks)

Chat memory persists under library/.chat/ (private, gitignored with the
rest of library/): each conversation is a session — turns in
sessions/<id>.jsonl, a sidecar sessions/<id>.json holding {id, title,
summary, talks, created, updated, claude_session_id} — and state.json
remembers which session is current. A pre-sessions history.jsonl is folded
into a first "Earlier conversation" session on startup (migrate_history).
When a session is left (a different one gets its first POST), a single
non-streamed call to whichever brain is cheap and up (ollama preferred)
writes its title + two-line summary into the sidecar; failures fall back
to the first user line as the title.

Ambient context: when "view" names a talk, the claude brain's prompt is
prefixed with one line naming that talk and its transcript path, and the
ollama brain's retrieval leads with that talk's chunks — "this talk" and
"what did he say" then mean the thing on screen. Past-tense recall goes
the other way: search_sessions scores keywords over stored turns and
summaries, exposed to the claude brain as `uv run tools/search_history.py`
(allowlisted) and to the ollama brain as the search_history tool.

Chat replies stream as chunked plain text (`text/plain; charset=utf-8`,
one raw text fragment per chunk — no SSE framing; the panel just appends
each decoded chunk with textContent). Failures BEFORE the stream starts
still return JSON {"error": ...} with a 4xx/5xx status; failures MID-stream
degrade gracefully: whatever text already arrived is kept and one plain
error sentence is appended.

Two brains:
    --brain claude (default)  runs the authenticated Claude CLI headless in
        this repo (`--output-format stream-json --include-partial-messages`),
        so it inherits the CLAUDE.md guide persona and can read library/
        itself. Agency is scoped: `--permission-mode default` plus an
        --allowedTools allowlist grant Edit/Write ONLY on STUDY.md,
        journal/**, library/**/notes.md, and library/INDEX.md, Bash ONLY
        for our reviewed tools (fetch_talk.py, speak.py, build_shelf.py,
        search_history.py), plus read-only WebSearch/WebFetch — no
        general Bash, nothing else. That is the safety boundary (see
        chat_allowed_tools).
        Conversation continuity via `--resume <session_id>`, falling back
        to folding trimmed history into the prompt.
    --brain ollama  talks to a local Ollama (http://localhost:11434) with
        "stream": true. Local models are weak rememberers, so the server
        does the remembering: a condensed guide persona + STUDY.md +
        library/INDEX.md + the top keyword-matched transcript chunks are
        packed into the system prompt. <think> blocks are filtered out of
        the stream (ThinkFilter). If the model supports tool calling
        (/api/show capabilities), it gets a bounded agency loop
        (ollama_tool_loop) over the same four reviewed tools the claude
        brain has — fetch_talk, rebuild_shelf, speak, search_history —
        every call passed through validate_tool_call (argv only, no
        shell). Models without tool support degrade gracefully: they are
        told they have no hands and answer normally.

Run with:
    uv run tools/serve_shelf.py                # then open http://localhost:8765
    uv run tools/serve_shelf.py --brain ollama --ollama-model qwen3

Tests (fastapi/uvicorn are lazy-imported, so plain pytest can load this file):
    uv run --with pytest pytest tools/tests/test_serve_shelf.py -v
"""

import argparse
import importlib.util
import json
import re
import shutil
import subprocess
import threading
import urllib.error
import urllib.parse
import urllib.request
import uuid
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LIBRARY = REPO_ROOT / "library"
CHAT_DIR = LIBRARY / ".chat"  # private: covered by the library/ gitignore
HISTORY_PATH = CHAT_DIR / "history.jsonl"  # pre-sessions thread (migrated)
SESSIONS_DIR = CHAT_DIR / "sessions"
STATE_PATH = CHAT_DIR / "state.json"
SESSION_ID_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")  # no dot-files, no slashes
SUMMARY_TIMEOUT = 120  # seconds for the one-shot leave-summary call
SEARCH_LIMIT = 8  # sessions returned by search_sessions
HISTORY_LIMIT = 50  # turns served back to the panel on page load
OLLAMA_URL = "http://localhost:11434"
CLAUDE_TIMEOUT = 600  # seconds — tool turns (ingest, TTS) take a while
TOOL_TIMEOUT = 600  # seconds per ollama tool subprocess
MAX_TOOL_ROUNDS = 4  # ollama tool-calling rounds per chat turn
CHUNK_SIZE = 1200
MAX_HISTORY_MESSAGES = 12

# Condensed from CLAUDE.md for local models that can't read the repo themselves.
GUIDE_PERSONA = """\
You are the guide of Second Arrow, a personal study space for learning
Buddhism and working with anger. You are a guide-teacher using real
teachings — not a coding assistant and not a syllabus.

How to respond:
- Angry or upset right now: keep it small — a short grounding practice,
  then ONE teaching drawn from the transcript excerpts below. No lecture.
- Curious, or wanting a story: offer a small tray — one talk or story, one
  plain-language concept, one practical reflection. Not more.
- Back from a talk: discuss it section by section — what landed, what
  confused, what met resistance.

Hard rules:
- Teach only from the transcript excerpts, notes, and memory given below.
  If the source is not there, say so plainly — never paraphrase a specific
  talk from training-data memory. The original audio is the authority.
- Anger is the root cluster (anger, aversion, patience, the two arrows).
- AA, NDEs, psychology, AI parallels are resonance, not doctrine.
- This is study material, not scripture, therapy, or medical advice.
Be warm and brief. Quote the transcripts when you can."""

STOPWORDS = frozenset(
    """a an and are as at be but by do does for from he had has have how i in
    is it its me my of on or she so that the their them they this to was we
    what when where which who why will with you your""".split()
)


class BrainError(Exception):
    """A user-facing brain failure: carries an HTTP status and a plain message."""

    def __init__(self, status: int, message: str):
        super().__init__(message)
        self.status = status
        self.message = message


# --- pure helpers (tested in tools/tests/test_serve_shelf.py) -----------


def chunk_transcript(text: str, size: int = CHUNK_SIZE) -> list[str]:
    """Split text into ~size-char chunks on word boundaries. No empty chunks."""
    chunks: list[str] = []
    current: list[str] = []
    length = 0
    for word in text.split():
        current.append(word)
        length += len(word) + 1
        if length >= size:
            chunks.append(" ".join(current))
            current, length = [], 0
    if current:
        chunks.append(" ".join(current))
    return chunks


def _keywords(text: str) -> set[str]:
    return {
        w
        for w in re.findall(r"[a-z']+", text.lower())
        if len(w) > 2 and w not in STOPWORDS
    }


def pick_chunks(
    question: str, transcripts: dict[str, str], k: int = 4
) -> list[tuple[str, str]]:
    """Top-k transcript chunks by keyword overlap with the question.

    transcripts maps talk title -> full transcript text. Returns
    (title, chunk) pairs, best first; chunks with no overlap are dropped.
    """
    terms = _keywords(question)
    scored: list[tuple[int, str, str]] = []
    for title, text in transcripts.items():
        for chunk in chunk_transcript(text):
            score = len(terms & _keywords(chunk))
            if score:
                scored.append((score, title, chunk))
    scored.sort(key=lambda item: -item[0])  # stable: ties keep shelf order
    return [(title, chunk) for _, title, chunk in scored[:k]]


def pick_chunks_for_view(
    question: str,
    transcripts: dict[str, str],
    view_title: str | None,
    k: int = 4,
) -> list[tuple[str, str]]:
    """pick_chunks, but the talk open on the shelf leads the retrieval.

    Its best-matching chunks come first; when the question shares no
    keywords with it at all, its opening chunk still leads (the model must
    know what "this talk" is). No view, or an unknown title, degrades to
    plain pick_chunks.
    """
    if not view_title or view_title not in transcripts:
        return pick_chunks(question, transcripts, k)
    lead = pick_chunks(question, {view_title: transcripts[view_title]}, k=2)
    if not lead:
        opening = chunk_transcript(transcripts[view_title])[:1]
        lead = [(view_title, chunk) for chunk in opening]
    rest = [pair for pair in pick_chunks(question, transcripts, k) if pair not in lead]
    return (lead + rest)[:k]


def ambient_prefix(view: str | None, titles: dict[str, str]) -> str:
    """One prompt line naming the talk open on the shelf, or "".

    titles maps slug -> display title (from INDEX.md). The line teaches the
    claude brain what "he" and "this talk" refer to, and where the
    transcript lives.
    """
    if not view or view not in titles:
        return ""
    return (
        f'[The user currently has "{titles[view]}" open on the shelf — its '
        f"transcript is library/{view}/transcript.md. Treat it as the ambient "
        'context; "he/this talk" refers to it.]'
    )


def build_system_prompt(
    study: str, index: str, chunks: list[tuple[str, str]], agency: str = ""
) -> str:
    parts = [GUIDE_PERSONA]
    if agency.strip():
        parts.append("## Acting in the world\n\n" + agency.strip())
    if study.strip():
        parts.append("## Study memory (STUDY.md)\n\n" + study.strip())
    if index.strip():
        parts.append("## Library index\n\n" + index.strip())
    if chunks:
        excerpts = "\n\n".join(
            f'### From "{title}"\n\n{chunk}' for title, chunk in chunks
        )
        parts.append("## Transcript excerpts (teach from these)\n\n" + excerpts)
    return "\n\n".join(parts)


def build_ollama_payload(
    messages: list[dict],
    model: str,
    study: str = "",
    index: str = "",
    chunks: list[tuple[str, str]] = (),
    stream: bool = False,
    tools: list | None = None,
    agency: str = "",
) -> dict:
    system = build_system_prompt(study, index, list(chunks), agency)
    payload = {
        "model": model,
        "messages": [{"role": "system", "content": system}, *messages],
        "stream": stream,
    }
    if tools:  # absent entirely when unused — some models choke on []
        payload["tools"] = list(tools)
    return payload


# The chat guide's durable memory: the ONLY paths it may write from chat.
# Everything else (code, curriculum, committed docs) needs a full session.
CHAT_WRITE_SCOPES = (
    "STUDY.md",
    "journal/**",
    "library/**/notes.md",
    "library/INDEX.md",
)

# The chat guide's hands: OUR reviewed tools, as exact command prefixes.
# `Bash(<prefix>:*)` allows `<prefix> <anything>` and nothing else — no
# general Bash (verified empirically: `Bash(echo hi:*)` lets `echo hi there`
# run while `ls /` stays blocked under --permission-mode default).
CHAT_BASH_SCOPES = (
    "uv run tools/fetch_talk.py",
    "uv run tools/speak.py",
    "uv run tools/build_shelf.py",
    "uv run tools/search_history.py",
)

# Read-only reach beyond the repo: current-world questions (teacher news,
# checking a link the user pasted). Teachings still enter the library only
# through an explicit fetch_talk the user asked for.
CHAT_READONLY_TOOLS = ("WebSearch", "WebFetch")


def chat_allowed_tools(
    scopes: tuple[str, ...] = CHAT_WRITE_SCOPES,
    bash_scopes: tuple[str, ...] = CHAT_BASH_SCOPES,
    readonly: tuple[str, ...] = CHAT_READONLY_TOOLS,
) -> str:
    """Comma-joined --allowedTools rules: Edit+Write per memory scope, Bash
    pinned to the reviewed tool commands, and the read-only web tools —
    nothing else.

    Verified against the real CLI: `--allowedTools "Edit(STUDY.md),..."`
    with `--permission-mode default` lets those through and leaves every
    other write/command pending-denied in headless mode. (This CLI version
    has no separate MultiEdit tool — Edit covers multi-edits.)
    """
    rules = [f"{tool}({scope})" for scope in scopes for tool in ("Edit", "Write")]
    rules += [f"Bash({command}:*)" for command in bash_scopes]
    rules += list(readonly)
    return ",".join(rules)


def build_claude_cmd(prompt: str, session_id: str | None = None) -> list[str]:
    cmd = [
        "claude",
        "-p",
        prompt,
        "--output-format",
        "stream-json",
        "--verbose",  # stream-json in -p mode requires it
        "--include-partial-messages",
        # A user-level defaultMode like "auto" would auto-accept ANY write;
        # pinning "default" makes the allowlist below the whole boundary.
        "--permission-mode",
        "default",
        "--allowedTools",
        chat_allowed_tools(),
    ]
    if session_id:
        cmd += ["--resume", session_id]
    return cmd


def trim_history(messages: list[dict], max_messages: int = MAX_HISTORY_MESSAGES) -> list[dict]:
    return list(messages[-max_messages:])


def history_prompt(messages: list[dict]) -> str:
    """Fold earlier turns into one prompt (first turn, or resume fallback)."""
    trimmed = trim_history(messages)
    if len(trimmed) == 1:
        return trimmed[0]["content"]
    lines = ["Earlier in this conversation:", ""]
    for message in trimmed[:-1]:
        who = "Student" if message["role"] == "user" else "Guide"
        lines.append(f"{who}: {message['content']}")
    lines += ["", f"Student: {trimmed[-1]['content']}"]
    return "\n".join(lines)


def parse_claude_output(stdout: str) -> tuple[str, str | None]:
    """Pull (reply, session_id) out of `claude --output-format json` stdout.

    Depending on CLI version the JSON is either a single result object or a
    list of events whose last "result"-typed item holds the reply. (The
    server itself now streams via parse_stream_line; this is the one-shot
    counterpart, kept for scripts and fallback use.)
    """
    data = json.loads(stdout)
    if isinstance(data, list):
        results = [item for item in data if item.get("type") == "result"]
        if not results:
            raise ValueError("no result event in claude output")
        data = results[-1]
    if data.get("is_error"):
        raise ValueError(str(data.get("result") or "claude reported an error"))
    return (data.get("result") or "").strip(), data.get("session_id")


def parse_stream_line(line: str) -> dict:
    """Parse one line of `claude -p --output-format stream-json` output.

    Returns {"text": str|None, "session_id": str|None, "done": bool}:
    text is a visible reply fragment (only content_block_delta/text_delta —
    thinking and signature deltas stay hidden), session_id rides on most
    events (the system/init event carries it first), done marks the final
    "result" event. Raises json.JSONDecodeError on a garbled line and
    ValueError when the result event reports is_error.
    """
    parsed: dict = {"text": None, "session_id": None, "done": False}
    line = line.strip()
    if not line:
        return parsed
    data = json.loads(line)
    if not isinstance(data, dict):
        return parsed
    session_id = data.get("session_id")
    if isinstance(session_id, str) and session_id:
        parsed["session_id"] = session_id
    if data.get("type") == "stream_event":
        event = data.get("event") or {}
        delta = event.get("delta") or {}
        if (
            event.get("type") == "content_block_delta"
            and delta.get("type") == "text_delta"
        ):
            parsed["text"] = delta.get("text") or None
    elif data.get("type") == "result":
        if data.get("is_error"):
            raise ValueError(str(data.get("result") or "claude reported an error"))
        parsed["done"] = True
    return parsed


def parse_ollama_stream_line(line: str) -> dict:
    """Parse one NDJSON line from Ollama /api/chat with "stream": true.

    Returns {"text": str|None, "done": bool, "tool_calls": list}. Tool
    calls arrive whole in a single chunk (verified live). Raises
    json.JSONDecodeError on a garbled line and ValueError when Ollama
    reports an error.
    """
    line = line.strip()
    if not line:
        return {"text": None, "done": False, "tool_calls": []}
    data = json.loads(line)
    if data.get("error"):
        raise ValueError(str(data["error"]))
    message = data.get("message", {})
    return {
        "text": message.get("content") or None,
        "done": bool(data.get("done")),
        "tool_calls": message.get("tool_calls") or [],
    }


def strip_think(text: str) -> str:
    """Drop <think>...</think> reasoning blocks some local models emit.

    One-shot counterpart of ThinkFilter (which handles streamed chunks).
    """
    return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()


def _partial_tag_suffix(text: str, tag: str) -> int:
    """Length of the longest suffix of text that is a proper prefix of tag."""
    for size in range(min(len(tag) - 1, len(text)), 0, -1):
        if tag.startswith(text[-size:]):
            return size
    return 0


class ThinkFilter:
    """strip_think for streams: drop <think>...</think> across chunk edges.

    feed() returns the visible part of each chunk, holding back any tail
    that might be the start of a split tag; flush() releases a held false
    alarm once the stream ends. Leading whitespace before the first visible
    text is swallowed so the bubble doesn't open with blank lines.
    """

    OPEN = "<think>"
    CLOSE = "</think>"

    def __init__(self) -> None:
        self._pending = ""
        self._in_think = False
        self._started = False

    def _emit(self, visible: str) -> str:
        if not self._started:
            visible = visible.lstrip()
        if visible:
            self._started = True
        return visible

    def feed(self, chunk: str) -> str:
        text = self._pending + chunk
        self._pending = ""
        out: list[str] = []
        while text:
            tag = self.CLOSE if self._in_think else self.OPEN
            index = text.find(tag)
            if index == -1:
                keep = _partial_tag_suffix(text, tag)
                if keep:
                    self._pending = text[-keep:]
                    text = text[:-keep]
                if not self._in_think:
                    out.append(text)
                text = ""
            elif self._in_think:
                self._in_think = False
                text = text[index + len(tag) :]
            else:
                out.append(text[:index])
                self._in_think = True
                text = text[index + len(tag) :]
        return self._emit("".join(out))

    def flush(self) -> str:
        visible = "" if self._in_think else self._pending
        self._pending = ""
        return self._emit(visible)


def resolve_ollama_model(configured: str, installed: list[str]) -> str:
    """Use the configured model if installed (tag-insensitive), else the first."""
    for name in installed:
        if name == configured or name.split(":")[0] == configured:
            return name
    return installed[0] if installed else configured


BRAIN_HINTS = {
    "claude": "the claude CLI is not on PATH — install Claude Code",
    "ollama": "run `ollama serve` and try again",
}


def resolve_brain(requested, default: str, available: dict) -> str:
    """Pick the brain for one chat turn (the panel's per-request toggle).

    No request falls back to the server default, un-second-guessed (probes
    can be stale; the default brain reports its own failures properly).
    An unknown name is a 400; an explicitly requested but unavailable
    brain is a 503 with a hint. Raises BrainError for both.
    """
    if not requested:
        return default
    if requested not in BRAIN_HINTS:
        names = " or ".join(f'"{name}"' for name in BRAIN_HINTS)
        raise BrainError(400, f"Unknown brain {requested!r} — use {names}.")
    if not available.get(requested, True):
        raise BrainError(
            503, f"The {requested} brain is not available — {BRAIN_HINTS[requested]}."
        )
    return requested


# --- ollama agency: validated tools + a bounded loop ----------------------
#
# The ollama brain mirrors the claude brain's scope exactly, no more:
# fetch_talk, rebuild_shelf, speak, search_history — four reviewed tools,
# argv-built, never shell=True. validate_tool_call is the entire boundary
# between a local model's output and subprocess.run.

OLLAMA_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "fetch_talk",
            "description": (
                "Ingest ONE talk into the library from a URL the user "
                "explicitly gave (captioned YouTube preferred). Never "
                "invent or guess URLs."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "url": {"type": "string", "description": "http(s) URL of the talk"},
                    "title": {"type": "string", "description": "talk title (optional)"},
                    "teacher": {"type": "string", "description": "teacher name (optional)"},
                    "themes": {"type": "string", "description": "comma-separated themes (optional)"},
                },
                "required": ["url"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "rebuild_shelf",
            "description": (
                "Regenerate the shelf page after any library change, "
                "then tell the user to refresh."
            ),
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "speak",
            "description": "Record a short reflection as an mp3 on the shelf.",
            "parameters": {
                "type": "object",
                "properties": {
                    "text": {"type": "string", "description": "the words to speak"},
                    "out_name": {"type": "string", "description": "short name for the audio file"},
                },
                "required": ["text", "out_name"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "search_history",
            "description": (
                "Search past conversations for something discussed before "
                "('that story we talked about'). Returns matching sessions "
                "with snippets."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "q": {"type": "string", "description": "a few keywords to look for"},
                },
                "required": ["q"],
            },
        },
    },
]

TOOL_PROGRESS = {
    "fetch_talk": "— fetching the talk… —",
    "rebuild_shelf": "— rebuilding the shelf… —",
    "speak": "— recording the audio… —",
    "search_history": "— searching past conversations… —",
}

AGENCY_TOOLS_NOTE = """\
You can act, sparingly, through four tools:
- fetch_talk: ingest ONE talk from a URL the user explicitly gave
  (captioned YouTube preferred). Never invent or guess URLs.
- rebuild_shelf: regenerate the shelf page after any library change,
  then tell the user to refresh.
- speak: record a short reflection as audio on the shelf.
- search_history: when the user refers to something you discussed in a
  past conversation, look it up instead of guessing.
Only use a tool when the user asks for the thing it does."""

AGENCY_NO_TOOLS_NOTE = """\
You cannot run tools in this setup — the local model serving you does
not support tool calls. If the user asks you to fetch or ingest a talk,
say so plainly and suggest switching to the claude brain or installing
a tools-capable local model (for example: ollama pull qwen3)."""

_FETCH_TEXT_FIELDS = (("title", "--title"), ("teacher", "--teacher"), ("themes", "--themes"))


def validate_tool_call(name: str, args) -> list[str]:
    """Turn a model's tool call into a safe argv list, or raise ValueError.

    This is the entire safety boundary for ollama agency: exact tool
    names only; fetch URLs must be http(s) with a hostname (no file://,
    no flag-shaped strings); free-text fields must be plain strings that
    don't open with a dash (no flag smuggling); speak output collapses
    to a bare slug pinned under library/ (no path traversal). The argv
    is executed directly — never shell=True, never string interpolation.
    """
    if not isinstance(args, dict):
        raise ValueError("arguments must be an object")
    if name == "rebuild_shelf":
        return ["uv", "run", "tools/build_shelf.py"]
    if name == "fetch_talk":
        url = args.get("url")
        if not isinstance(url, str):
            raise ValueError("url must be a string")
        parsed = urllib.parse.urlsplit(url)
        if parsed.scheme not in ("http", "https") or not parsed.hostname:
            raise ValueError("url must be http(s) with a hostname")
        argv = ["uv", "run", "tools/fetch_talk.py", url]
        for key, flag in _FETCH_TEXT_FIELDS:
            value = args.get(key)
            if value in (None, ""):
                continue
            if not isinstance(value, str) or value.lstrip().startswith("-"):
                raise ValueError(f"{key} must be plain text")
            argv += [flag, value]
        return argv
    if name == "speak":
        text = args.get("text")
        if not isinstance(text, str) or not text.strip() or text.lstrip().startswith("-"):
            raise ValueError("text must be plain, non-empty text")
        out_name = args.get("out_name")
        if not isinstance(out_name, str):
            raise ValueError("out_name must be a string")
        slug = re.sub(r"[^a-z0-9]+", "-", out_name.lower()).strip("-")
        if not slug:
            raise ValueError("out_name must contain letters or digits")
        return ["uv", "run", "tools/speak.py", "--text", text, "-o", f"library/{slug}.mp3"]
    if name == "search_history":
        q = args.get("q")
        if not isinstance(q, str) or not q.strip() or q.lstrip().startswith("-"):
            raise ValueError("q must be plain, non-empty text")
        return ["uv", "run", "tools/search_history.py", q]
    raise ValueError(f"unknown tool {name!r}")


def parse_tool_calls(message: dict) -> list[tuple[str, dict]]:
    """(name, arguments) pairs from an Ollama assistant message.

    Arguments usually arrive as a dict; some models send a JSON string.
    Junk calls come through as ("", {}) so validate_tool_call can reject
    them with a message the model gets to read.
    """
    calls: list[tuple[str, dict]] = []
    for call in message.get("tool_calls") or []:
        function = call.get("function") or {}
        name = function.get("name")
        args = function.get("arguments")
        if isinstance(args, str):
            try:
                args = json.loads(args)
            except json.JSONDecodeError:
                args = None
        calls.append(
            (name if isinstance(name, str) else "", args if isinstance(args, dict) else {})
        )
    return calls


def resolve_agent_model(
    configured: str, installed: list[str], capable: list[str]
) -> tuple[str, bool]:
    """(model, can_call_tools) for the ollama brain.

    An explicitly configured, installed model is respected even without
    tool support (agency then degrades gracefully). When we're falling
    back anyway, prefer an installed tools-capable model over the plain
    first-installed default.
    """
    model = resolve_ollama_model(configured, installed)
    matches_configured = (
        model == configured or model.split(":")[0] == configured.split(":")[0]
    )
    if model in capable or matches_configured:
        return model, model in capable
    for name in installed:
        if name in capable:
            return name, True
    return model, False


def ollama_tool_loop(
    response,
    transcript: list[dict],
    model: str,
    opener,
    runner,
    tools: list | None = None,
    max_rounds: int = MAX_TOOL_ROUNDS,
):
    """Bounded tool-calling loop over streamed Ollama rounds (a generator).

    `response` is the already-open first-round stream (NDJSON iterable +
    context manager); `opener(payload)` opens each next round; `runner
    (argv) -> (ok, summary)` executes a validated tool. Text deltas
    stream straight through (so the final reply arrives incrementally,
    and a plain turn never pays for the loop); a small progress line is
    yielded while each tool runs. On a rejected or failed tool the error
    is fed back for ONE tool-less round so the model can explain, then
    the turn ends. `transcript` grows assistant/tool messages in place.

    Note: the design brief said non-streamed tool rounds; live Ollama
    delivers tool_calls whole inside a streamed round, so rounds stay
    streamed — same bound, better panel feedback.
    """
    think = ThinkFilter()
    allow_tools = bool(tools)
    rounds = 0
    while True:
        content_parts: list[str] = []
        raw_calls: list[dict] = []
        with response:
            for raw in response:
                parsed = parse_ollama_stream_line(raw.decode("utf-8", "replace"))
                raw_calls.extend(parsed["tool_calls"])
                if parsed["text"]:
                    content_parts.append(parsed["text"])
                    visible = think.feed(parsed["text"])
                    if visible:
                        yield visible
                if parsed["done"]:
                    break
        calls = parse_tool_calls({"tool_calls": raw_calls}) if allow_tools else []
        if not calls:
            break  # the text just streamed was the final reply
        rounds += 1
        failed = False
        transcript.append(
            {"role": "assistant", "content": "".join(content_parts), "tool_calls": raw_calls}
        )
        for name, args in calls:
            yield "\n" + TOOL_PROGRESS.get(name, f"— running {name}… —") + "\n"
            try:
                argv = validate_tool_call(name, args)
            except ValueError as error:
                failed = True
                result = f"Tool call rejected: {error}"
            else:
                ok, result = runner(argv)
                failed = failed or not ok
            transcript.append({"role": "tool", "tool_name": name, "content": result})
        allow_tools = not failed and rounds < max_rounds
        payload = {"model": model, "messages": transcript, "stream": True}
        if allow_tools:
            payload["tools"] = list(tools)
        response = opener(payload)
    tail = think.flush()
    if tail:
        yield tail


# --- persistent chat memory (library/.chat/, private) --------------------


def append_turn(
    path: Path, role: str, content: str, brain: str, timestamp: str | None = None
) -> None:
    """Append one completed chat turn to the JSONL history file."""
    record = {
        "role": role,
        "content": content,
        "brain": brain,
        "ts": timestamp
        or datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, ensure_ascii=False) + "\n")


def load_history(path: Path, limit: int = HISTORY_LIMIT) -> list[dict]:
    """Last `limit` turns from the JSONL history. Corrupt lines are skipped
    (a torn write must never take the whole panel down)."""
    if not path.exists():
        return []
    turns: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError:
            continue
        if (
            isinstance(record, dict)
            and isinstance(record.get("role"), str)
            and isinstance(record.get("content"), str)
        ):
            turns.append(record)
    return turns[-limit:]


def load_chat_state(path: Path) -> dict:
    """Chat state (the claude session_id) so continuity survives restarts."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError):
        return {}


def save_chat_state(path: Path, state: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state), encoding="utf-8")


# --- sessions: one conversation per file, a sidecar of meta -----------------


def session_turns_path(sessions_dir: Path, sid: str) -> Path:
    return sessions_dir / f"{sid}.jsonl"


def session_meta_path(sessions_dir: Path, sid: str) -> Path:
    return sessions_dir / f"{sid}.json"


def load_session_meta(path: Path) -> dict:
    """The session sidecar, or {} — same tolerance as load_chat_state."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError):
        return {}


def save_session_meta(path: Path, meta: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(meta, ensure_ascii=False), encoding="utf-8")


def fallback_title(text: str, limit: int = 60) -> str:
    """First user line as a display title: whitespace collapsed, capped."""
    flat = " ".join(text.split())
    return flat if len(flat) <= limit else flat[:limit].rstrip() + "…"


def new_session_id() -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    return f"{stamp}-{uuid.uuid4().hex[:4]}"


def update_session_meta(
    meta_path: Path,
    claude_session_id: str | None = None,
    talk: str | None = None,
    fallback_title_text: str = "",
) -> dict:
    """Refresh a session's sidecar after a completed turn.

    Creates it on first use (id from the filename, created/updated stamps,
    the first user line as a provisional title). The ambient talk joins
    meta["talks"]; the claude thread id is kept current so the conversation
    can be resumed. A leave-summary later overwrites title/summary.
    """
    meta = load_session_meta(meta_path)
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    meta.setdefault("id", meta_path.stem)
    meta.setdefault("created", now)
    meta["updated"] = now
    meta.setdefault("summary", "")
    if not meta.get("title") and fallback_title_text:
        meta["title"] = fallback_title(fallback_title_text)
    talks = [t for t in meta.get("talks") or [] if isinstance(t, str)]
    if talk and talk not in talks:
        talks.append(talk)
    meta["talks"] = talks
    if claude_session_id:
        meta["claude_session_id"] = claude_session_id
    save_session_meta(meta_path, meta)
    return meta


def _first_user_line(turns_path: Path) -> str:
    for turn in load_history(turns_path, limit=10**6):
        if turn.get("role") == "user":
            return turn["content"]
    return ""


def list_sessions(sessions_dir: Path) -> list[dict]:
    """[{id, title, summary, updated}] for every stored session, newest
    first. Missing sidecars degrade to the first user line + file mtime."""
    if not sessions_dir.is_dir():
        return []
    sessions: list[dict] = []
    for turns_path in sessions_dir.glob("*.jsonl"):
        sid = turns_path.stem
        meta = load_session_meta(session_meta_path(sessions_dir, sid))
        title = meta.get("title") or fallback_title(_first_user_line(turns_path))
        updated = meta.get("updated") or datetime.fromtimestamp(
            turns_path.stat().st_mtime, tz=timezone.utc
        ).isoformat(timespec="seconds")
        sessions.append(
            {
                "id": sid,
                "title": title or "Conversation",
                "summary": meta.get("summary") or "",
                "updated": updated,
            }
        )
    sessions.sort(key=lambda s: s["updated"], reverse=True)
    return sessions


def migrate_history(chat_dir: Path) -> str | None:
    """Fold a pre-sessions history.jsonl into a first session, once.

    The legacy thread becomes sessions/earlier-conversation.jsonl with a
    ready-made sidecar; the old claude session_id (state.json) rides along
    so the thread continues seamlessly. Returns the new session id, or
    None when there is nothing to migrate.
    """
    legacy = chat_dir / "history.jsonl"
    if not legacy.exists():
        return None
    sessions_dir = chat_dir / "sessions"
    sessions_dir.mkdir(parents=True, exist_ok=True)
    sid, counter = "earlier-conversation", 1
    while session_turns_path(sessions_dir, sid).exists():
        counter += 1
        sid = f"earlier-conversation-{counter}"
    legacy.rename(session_turns_path(sessions_dir, sid))
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    meta = {
        "id": sid,
        "title": "Earlier conversation",
        "summary": "",
        "talks": [],
        "created": now,
        "updated": now,
    }
    old_session = load_chat_state(chat_dir / "state.json").get("session_id")
    if old_session:
        meta["claude_session_id"] = old_session
    save_session_meta(session_meta_path(sessions_dir, sid), meta)
    return sid


def resolve_session(requested, current: str | None, sessions_dir: Path) -> str:
    """Pick the session for one chat turn.

    None/"" → the server's current session, else the most recent stored
    one, else a fresh id. "new" always mints a fresh id (its empty sidecar
    means a fresh claude thread too). A named session must be a safe id
    (400) and exist (404). Raises BrainError — same shape the brain
    resolution uses.
    """
    if requested in (None, ""):
        if current:
            return current
        stored = list_sessions(sessions_dir)
        return stored[0]["id"] if stored else new_session_id()
    if not isinstance(requested, str):
        raise BrainError(400, "session must be a string")
    if requested == "new":
        return new_session_id()
    if not SESSION_ID_RE.fullmatch(requested):
        raise BrainError(400, f"invalid session id {requested!r}")
    if not session_turns_path(sessions_dir, requested).exists():
        raise BrainError(404, f"no session {requested!r}")
    return requested


# --- leave-summaries ---------------------------------------------------------


def summarize_prompt(turns: list[dict], limit: int = 20, clip: int = 400) -> str:
    """The one-shot ask that turns a left-behind session into title+summary."""
    lines = [
        "Condense this conversation between a student and their Buddhist",
        "study guide. Reply with exactly two lines, nothing else:",
        "Title: <at most eight words>",
        "Summary: <one or two short sentences>",
        "",
        "Conversation:",
    ]
    for turn in turns[-limit:]:
        who = "Student" if turn.get("role") == "user" else "Guide"
        lines.append(f"{who}: {turn.get('content', '')[:clip]}")
    return "\n".join(lines)


def parse_summary(text: str) -> tuple[str | None, str | None]:
    """(title, summary) out of a brain's reply; (None, None) when unfindable.

    Tolerates case and light markdown dressing around the labels.
    """

    def find(label: str) -> str | None:
        match = re.search(
            rf"^[\s*_#>-]*{label}[\s*_]*:[\s*_]*(.+)$", text, re.I | re.M
        )
        if not match:
            return None
        value = match.group(1).strip().strip("*_").strip()
        return value or None

    return find("title"), find("summary")


def _ask_ollama_once(prompt: str, configured_model: str) -> str:
    tags = _ollama_json("/api/tags", timeout=5)
    installed = [m["name"] for m in tags.get("models", [])]
    if not installed:
        raise BrainError(503, "ollama has no models")
    model = resolve_ollama_model(configured_model, installed)
    data = _ollama_json(
        "/api/chat",
        {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "stream": False,
        },
        timeout=SUMMARY_TIMEOUT,
    )
    return strip_think(data.get("message", {}).get("content") or "")


def _ask_claude_once(prompt: str) -> str:
    proc = subprocess.run(
        ["claude", "-p", prompt, "--output-format", "json", "--permission-mode", "default"],
        cwd=REPO_ROOT,
        stdin=subprocess.DEVNULL,
        capture_output=True,
        text=True,
        timeout=SUMMARY_TIMEOUT,
    )
    if proc.returncode != 0:
        raise BrainError(503, f"claude exited {proc.returncode}")
    return parse_claude_output(proc.stdout)[0]


def ask_cheap_brain(prompt: str, ollama_model: str = "qwen3") -> str:
    """ONE non-streamed reply from whichever brain is cheap and up.

    Ollama is preferred (local, free); the claude CLI is the fallback.
    Raises when neither is available — the caller tolerates failure.
    """
    available = probe_brains()
    if available.get("ollama"):
        return _ask_ollama_once(prompt, ollama_model)
    if available.get("claude"):
        return _ask_claude_once(prompt)
    raise BrainError(503, "no brain available to summarize")


def summarize_session(
    sid: str,
    sessions_dir: Path = SESSIONS_DIR,
    ollama_model: str = "qwen3",
    ask=None,
) -> None:
    """Write a left session's title + summary into its sidecar, best-effort.

    Skips empty and already-summarized sessions. Any failure (no brain,
    timeout, unparseable reply) leaves the sidecar as it was — the first
    user line already serves as the fallback title.
    """
    turns = load_history(session_turns_path(sessions_dir, sid), limit=10**6)
    if not turns:
        return
    meta_path = session_meta_path(sessions_dir, sid)
    meta = load_session_meta(meta_path)
    if meta.get("summary"):
        return
    try:
        reply = (ask or (lambda p: ask_cheap_brain(p, ollama_model)))(
            summarize_prompt(turns)
        )
        title, summary = parse_summary(reply)
    except Exception as error:  # noqa: BLE001 — summaries are best-effort by design
        print(f"[serve_shelf] summary for {sid!r} failed: {error}")
        return
    if not title and not summary:
        print(f"[serve_shelf] summary for {sid!r} unparseable — keeping the fallback title")
        return
    meta.setdefault("id", sid)
    if title:
        meta["title"] = title
    if summary:
        meta["summary"] = summary
    save_session_meta(meta_path, meta)


# --- recall: keyword search over stored sessions ------------------------------


def _snippet(text: str, terms: set[str], width: int = 180) -> str:
    """A readable window around the first matched term."""
    flat = " ".join(text.split())
    lower = flat.lower()
    hits = [lower.find(term) for term in terms if lower.find(term) != -1]
    index = min(hits) if hits else 0
    start = max(0, index - width // 3)
    piece = flat[start : start + width].strip()
    prefix = "…" if start > 0 else ""
    suffix = "…" if start + width < len(flat) else ""
    return f"{prefix}{piece}{suffix}"


def search_sessions(q: str, sessions_dir: Path, limit: int = SEARCH_LIMIT) -> list[dict]:
    """Keyword-scored recall over stored turns and summaries.

    Returns [{session_id, title, snippet, when}], best score first (ties:
    most recent first). The snippet comes from the best-matching text —
    a turn or the stored title+summary line.
    """
    terms = _keywords(q)
    if not terms:
        return []
    results: list[dict] = []
    for info in list_sessions(sessions_dir):
        texts = [f'{info["title"]} {info["summary"]}']
        texts += [
            turn["content"]
            for turn in load_history(
                session_turns_path(sessions_dir, info["id"]), limit=10**6
            )
        ]
        best_score, best_text = 0, ""
        for text in texts:
            score = len(terms & _keywords(text))
            if score > best_score:
                best_score, best_text = score, text
        if best_score:
            results.append(
                {
                    "score": best_score,
                    "session_id": info["id"],
                    "title": info["title"],
                    "snippet": _snippet(best_text, terms),
                    "when": info["updated"],
                }
            )
    results.sort(key=lambda r: r["when"], reverse=True)
    results.sort(key=lambda r: -r["score"])  # stable: ties stay newest-first
    return [
        {key: r[key] for key in ("session_id", "title", "snippet", "when")}
        for r in results[:limit]
    ]


def record_stream(
    stream,
    user_content: str,
    chosen: str,
    state: dict,
    turns_path: Path,
    meta_path: Path,
    view: str | None = None,
):
    """Pass a reply stream through while persisting the completed turn.

    Once the stream finishes, the user message and the full reply are
    appended to the session's turns and its sidecar is refreshed (updated
    stamp, ambient talk, claude thread id) — so the conversation survives
    page closes and server restarts. An empty reply records nothing: no
    ghost sessions.
    """
    parts: list[str] = []
    for chunk in stream:
        parts.append(chunk)
        yield chunk
    reply = "".join(parts)
    if reply.strip():
        append_turn(turns_path, "user", user_content, chosen)
        append_turn(turns_path, "assistant", reply, chosen)
        update_session_meta(
            meta_path,
            claude_session_id=state.get("session_id"),
            talk=view,
            fallback_title_text=user_content,
        )


# --- shelf + library ----------------------------------------------------


def load_build_shelf():
    path = Path(__file__).resolve().parent / "build_shelf.py"
    spec = importlib.util.spec_from_file_location("build_shelf", path)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


def rebuild_shelf(library: Path) -> Path:
    build_shelf = load_build_shelf()
    reach = build_shelf.collect_reach(library.parent / "curriculum")
    output = library / "shelf.html"
    output.write_text(build_shelf.render_shelf(library, reach))
    return output


def load_transcripts(library: Path) -> dict[str, str]:
    """Map talk title (from INDEX.md, slug fallback) -> transcript text."""
    build_shelf = load_build_shelf()
    transcripts: dict[str, str] = {}
    for talk in build_shelf.parse_index((library / "INDEX.md").read_text()):
        path = library / talk["slug"] / "transcript.md"
        if path.exists():
            transcripts[talk.get("title", talk["slug"])] = path.read_text()
    return transcripts


def load_talk_titles(library: Path) -> dict[str, str]:
    """Map talk slug -> display title (for ambient context)."""
    build_shelf = load_build_shelf()
    return {
        talk["slug"]: talk.get("title", talk["slug"])
        for talk in build_shelf.parse_index((library / "INDEX.md").read_text())
    }


# --- the two brains (both stream) ----------------------------------------

STREAM_BROKE = "the stream broke off here. Ask again and I'll pick it back up."


def probe_brains(ollama_timeout: float = 1.0) -> dict:
    """Cheap availability map for /health and the panel's brain toggle.

    claude: is the CLI on PATH (instant). ollama: does /api/tags answer
    within ~1s (connection-refused on localhost fails immediately, so a
    stopped Ollama doesn't stall the probe).
    """
    available = {"claude": shutil.which("claude") is not None, "ollama": False}
    try:
        with urllib.request.urlopen(
            OLLAMA_URL + "/api/tags", timeout=ollama_timeout
        ):
            available["ollama"] = True
    except (urllib.error.URLError, OSError, TimeoutError):
        pass
    return available


def _spawn_claude(prompt: str, session_id: str | None) -> subprocess.Popen:
    try:
        return subprocess.Popen(
            build_claude_cmd(prompt, session_id),
            cwd=REPO_ROOT,
            stdin=subprocess.DEVNULL,  # claude -p waits on a dangling stdin pipe
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            bufsize=1,  # line-buffered: one stream-json event per readline
        )
    except FileNotFoundError:
        raise BrainError(503, "The claude CLI is not on PATH — install Claude Code.")


def _drain_claude(proc: subprocess.Popen, state: dict):
    """Yield text deltas from a running claude stream-json process.

    Generator-returns (emitted_any_text, finished_cleanly). A single
    garbled line is skipped; an is_error result or a bad exit just flips
    the flag — the caller decides how to apologise.
    """
    emitted, finished = False, False
    watchdog = threading.Timer(CLAUDE_TIMEOUT, proc.kill)
    watchdog.start()
    try:
        assert proc.stdout is not None
        for line in proc.stdout:
            try:
                event = parse_stream_line(line)
            except json.JSONDecodeError:
                continue  # one garbled line shouldn't sink the reply
            except ValueError:
                break  # the CLI reported an error result
            if event["session_id"]:
                state["session_id"] = event["session_id"]
            if event["text"]:
                emitted = True
                yield event["text"]
            if event["done"]:
                finished = True
        proc.wait(timeout=10)
    except (OSError, subprocess.TimeoutExpired):
        pass
    finally:
        watchdog.cancel()
        if proc.poll() is None:
            proc.kill()
            proc.wait()
    return emitted, finished and proc.returncode == 0


def stream_claude(messages: list[dict], state: dict, prefix: str = ""):
    """Start a claude turn; return a generator of reply-text chunks.

    `prefix` (the ambient-context line) rides at the top of the outgoing
    prompt when present. Raises BrainError before any output if the CLI
    can't even start. Mid-stream failures degrade gracefully: a resume
    that dies before producing text is retried fresh with folded history
    (resume has proved flaky); anything else keeps what arrived and
    appends one apology.
    """

    def with_prefix(prompt: str) -> str:
        return f"{prefix}\n\n{prompt}" if prefix else prompt

    session_id = state.get("session_id")
    prompt = messages[-1]["content"] if session_id else history_prompt(messages)
    proc = _spawn_claude(with_prefix(prompt), session_id)

    def generate():
        emitted, ok = yield from _drain_claude(proc, state)
        if not ok and not emitted and session_id:
            state["session_id"] = None  # retry fresh with folded history
            try:
                retry = _spawn_claude(with_prefix(history_prompt(messages)), None)
            except BrainError as error:
                yield f"The guide is out of reach — {error.message}"
                return
            emitted, ok = yield from _drain_claude(retry, state)
        if not ok:
            yield ("\n\n— " if emitted else "The guide is out of reach — ") + STREAM_BROKE
        elif not emitted:
            yield "The guide said nothing this time — try asking again."

    return generate()


def _ollama_json(path: str, payload: dict | None = None, timeout: int = 240) -> dict:
    request = urllib.request.Request(
        OLLAMA_URL + path,
        data=json.dumps(payload).encode() if payload is not None else None,
        headers={"Content-Type": "application/json"} if payload is not None else {},
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return json.loads(response.read())


def _open_ollama_chat(payload: dict, timeout: int = 120):
    """Open a streamed /api/chat POST; returns the live HTTP response."""
    request = urllib.request.Request(
        OLLAMA_URL + "/api/chat",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"},
    )
    return urllib.request.urlopen(request, timeout=timeout)


_TOOLS_CAPABLE: dict[str, bool] = {}  # per-process cache, keyed by model name


def model_supports_tools(model: str) -> bool:
    """Does this installed model support tool calling? (/api/show, cached).

    Ollama reports a "capabilities" list per model — cheap and reliable,
    where merely sending a `tools` parameter is not (the API accepts it
    silently even for models that will never emit a tool call).
    """
    if model not in _TOOLS_CAPABLE:
        try:
            data = _ollama_json("/api/show", {"model": model}, timeout=10)
            capabilities = data.get("capabilities") or []
        except (urllib.error.URLError, OSError, TimeoutError, json.JSONDecodeError):
            capabilities = []
        _TOOLS_CAPABLE[model] = "tools" in capabilities
    return _TOOLS_CAPABLE[model]


def run_tool(argv: list[str], timeout: int = TOOL_TIMEOUT) -> tuple[bool, str]:
    """Execute a validated tool argv; (ok, short summary for the model)."""
    try:
        proc = subprocess.run(
            argv,
            cwd=REPO_ROOT,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return False, f"{argv[2]} timed out after {timeout}s."
    except OSError as error:
        return False, f"{argv[2]} could not start: {error}"
    tail = ((proc.stdout or "") + "\n" + (proc.stderr or "")).strip()[-1500:]
    if proc.returncode != 0:
        return False, f"{argv[2]} failed (exit {proc.returncode}):\n{tail}"
    return True, f"{argv[2]} succeeded:\n{tail}"


def stream_ollama(
    messages: list[dict], configured_model: str, library: Path, view: str | None = None
):
    """Start an Ollama turn; return a generator of reply-text chunks.

    Pre-flight (reachability, model resolution, opening the streamed POST)
    raises BrainError so the endpoint can still answer with a proper JSON
    error; once streaming, failures keep what arrived plus one apology.
    <think> blocks are filtered out on the way through (ThinkFilter).

    Agency: when the resolved model supports tool calling (/api/show
    capabilities), the turn runs through ollama_tool_loop with the three
    validated tools; otherwise the model is told it has no hands and the
    turn is a plain retrieval-grounded reply. Retrieval is identical in
    both modes.
    """
    try:
        tags = _ollama_json("/api/tags", timeout=5)
    except (urllib.error.URLError, OSError, TimeoutError):
        raise BrainError(
            503,
            "Ollama is not reachable at localhost:11434 — "
            "run `ollama serve` and try again.",
        )
    installed = [m["name"] for m in tags.get("models", [])]
    if not installed:
        raise BrainError(
            503,
            "Ollama is running but has no models — "
            f"try `ollama pull {configured_model}`.",
        )
    capable = [name for name in installed if model_supports_tools(name)]
    model, has_tools = resolve_agent_model(configured_model, installed, capable)
    if model.split(":")[0] != configured_model.split(":")[0]:
        print(
            f"[serve_shelf] {configured_model!r} not installed; using {model!r}"
            f" (tools: {'yes' if has_tools else 'no'})"
        )

    study_path = library.parent / "STUDY.md"
    study = study_path.read_text() if study_path.exists() else ""
    index = (library / "INDEX.md").read_text()
    # The talk open on the shelf leads retrieval — "this talk" means it.
    view_title = load_talk_titles(library).get(view) if view else None
    chunks = pick_chunks_for_view(
        messages[-1]["content"], load_transcripts(library), view_title, k=4
    )
    payload = build_ollama_payload(
        trim_history(messages),
        model,
        study,
        index,
        chunks,
        stream=True,
        tools=OLLAMA_TOOLS if has_tools else None,
        agency=AGENCY_TOOLS_NOTE if has_tools else AGENCY_NO_TOOLS_NOTE,
    )
    try:  # urlopen returns once headers arrive; the body then streams NDJSON
        response = _open_ollama_chat(payload)
    except (urllib.error.URLError, OSError, TimeoutError):
        raise BrainError(
            503,
            "Ollama stopped answering mid-conversation — "
            "check `ollama serve` and try again.",
        )

    def generate():
        emitted = False
        try:
            for chunk in ollama_tool_loop(
                response,
                payload["messages"],
                model,
                _open_ollama_chat,
                run_tool,
                tools=OLLAMA_TOOLS if has_tools else None,
            ):
                emitted = True
                yield chunk
            if not emitted:
                yield f"Ollama ({model}) returned an empty reply — try again."
        except (json.JSONDecodeError, ValueError, urllib.error.URLError, OSError, TimeoutError):
            yield ("\n\n— " if emitted else "The guide is out of reach — ") + STREAM_BROKE

    return generate()


# --- the server ---------------------------------------------------------


def create_app(brain: str, ollama_model: str):
    from fastapi import FastAPI
    from fastapi.responses import FileResponse, JSONResponse, StreamingResponse
    from fastapi.staticfiles import StaticFiles

    shelf = rebuild_shelf(LIBRARY)
    print(f"[serve_shelf] rebuilt {shelf}")

    app = FastAPI(title="Second Arrow — Study Shelf")
    # A pre-sessions history.jsonl becomes the first session, once; the
    # current session survives restarts via state.json {"current": id}.
    migrated = migrate_history(CHAT_DIR)
    if migrated:
        print(f"[serve_shelf] migrated legacy history into session {migrated!r}")
    current: dict = {"sid": load_chat_state(STATE_PATH).get("current") or migrated}
    if current["sid"]:
        save_chat_state(STATE_PATH, {"current": current["sid"]})
        print(f"[serve_shelf] current session {current['sid']}")

    def leave_session(sid: str) -> None:
        """Summarize a left-behind session in the background, best-effort."""
        threading.Thread(
            target=summarize_session,
            args=(sid, SESSIONS_DIR, ollama_model),
            daemon=True,
        ).start()

    @app.get("/")
    def index() -> FileResponse:
        return FileResponse(LIBRARY / "shelf.html", media_type="text/html")

    @app.get("/health")
    def health() -> dict:
        return {"ok": True, "brain": brain, "brains": probe_brains()}

    @app.get("/api/sessions")
    def api_sessions() -> dict:
        return {"sessions": list_sessions(SESSIONS_DIR), "current": current["sid"]}

    @app.get("/api/history")
    def api_history(session: str | None = None):
        try:
            sid = resolve_session(session, current["sid"], SESSIONS_DIR)
        except BrainError as error:
            return JSONResponse({"error": error.message}, status_code=error.status)
        turns = load_history(session_turns_path(SESSIONS_DIR, sid), HISTORY_LIMIT)
        return {"session": sid, "turns": turns}

    @app.post("/api/chat")
    def chat(body: dict):
        messages = body.get("messages")
        if (
            not isinstance(messages, list)
            or not messages
            or not all(
                isinstance(m, dict)
                and m.get("role") in ("user", "assistant")
                and isinstance(m.get("content"), str)
                for m in messages
            )
            or messages[-1]["role"] != "user"
        ):
            return JSONResponse(
                {"error": "Body must be {\"messages\": [...]} ending with a user message."},
                status_code=422,
            )
        view = body.get("view") if isinstance(body.get("view"), str) else None
        try:
            sid = resolve_session(body.get("session"), current["sid"], SESSIONS_DIR)
            chosen = resolve_brain(body.get("brain"), brain, probe_brains())
        except BrainError as error:
            return JSONResponse({"error": error.message}, status_code=error.status)
        if current["sid"] and current["sid"] != sid:
            leave_session(current["sid"])  # its title+summary get written
        current["sid"] = sid
        save_chat_state(STATE_PATH, {"current": sid})
        # Each session carries its own claude thread in its sidecar, so
        # switching sessions switches threads; ollama turns never touch it.
        meta = load_session_meta(session_meta_path(SESSIONS_DIR, sid))
        state = {"session_id": meta.get("claude_session_id")}
        try:
            if chosen == "claude":
                prefix = ambient_prefix(view, load_talk_titles(LIBRARY))
                stream = stream_claude(messages, state, prefix=prefix)
            else:
                stream = stream_ollama(messages, ollama_model, LIBRARY, view=view)
        except BrainError as error:
            return JSONResponse({"error": error.message}, status_code=error.status)
        # Chunked plain text: each chunk is a raw reply fragment (no framing).
        return StreamingResponse(
            record_stream(
                stream,
                messages[-1]["content"],
                chosen,
                state,
                turns_path=session_turns_path(SESSIONS_DIR, sid),
                meta_path=session_meta_path(SESSIONS_DIR, sid),
                view=view,
            ),
            media_type="text/plain; charset=utf-8",
            headers={"X-Brain": chosen, "X-Session": sid},
        )

    # Mounted last so /, /health, /api/chat win; everything else — primers,
    # talk audio, transcripts — is served straight from library/ with Range
    # support, matching the shelf's relative srcs.
    app.mount("/", StaticFiles(directory=LIBRARY), name="library")
    return app


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve the study shelf with a guide chat.")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--brain", choices=("claude", "ollama"), default="claude")
    parser.add_argument("--ollama-model", default="qwen3")
    args = parser.parse_args()

    if not (LIBRARY / "INDEX.md").exists():
        raise SystemExit(f"No {LIBRARY / 'INDEX.md'} found — ingest a talk first.")

    import uvicorn

    app = create_app(args.brain, args.ollama_model)
    print(f"[serve_shelf] guide brain: {args.brain}")
    print(f"[serve_shelf] open http://localhost:{args.port}")
    uvicorn.run(app, host="127.0.0.1", port=args.port)


if __name__ == "__main__":
    main()
