#!/usr/bin/env python3
# /// script
# dependencies = ["fastapi", "uvicorn"]
# ///
"""Serve the study shelf with a guide chat panel.

Binds 127.0.0.1 only. On startup the shelf page is regenerated by importing
the sibling build_shelf.py by path (importlib, the same pattern the tests
use) rather than shelling out through `uv run` — build_shelf is stdlib-only,
so importing it is fast, in-process, and fails loudly if it breaks.

Routes:
    GET  /          the shelf page (library/shelf.html, freshly rebuilt)
    GET  /health    {"ok": true, "brain": "claude"|"ollama"}
    POST /api/chat  {"messages": [{"role", "content"}, ...]} -> {"reply", "brain"}
    /<talk>/...     library/ served statically (Range supported, audio seeks)

Two brains:
    --brain claude (default)  runs the authenticated Claude CLI headless in
        this repo, so it inherits the CLAUDE.md guide persona and can read
        library/ itself. Headless mode auto-denies writes/Bash — that is the
        safety boundary. Conversation continuity via `--resume <session_id>`,
        falling back to folding trimmed history into the prompt.
    --brain ollama  talks to a local Ollama (http://localhost:11434). Local
        models are weak rememberers, so the server does the remembering: a
        condensed guide persona + STUDY.md + library/INDEX.md + the top
        keyword-matched transcript chunks are packed into the system prompt.

Run with:
    uv run tools/serve_shelf.py                # then open http://localhost:8765
    uv run tools/serve_shelf.py --brain ollama --ollama-model qwen3

Tests (fastapi/uvicorn are lazy-imported, so plain pytest can load this file):
    uv run --with pytest pytest tools/tests/test_serve_shelf.py -v
"""

import argparse
import importlib.util
import json
import re
import subprocess
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LIBRARY = REPO_ROOT / "library"
OLLAMA_URL = "http://localhost:11434"
CLAUDE_TIMEOUT = 240  # seconds — guide turns can take a while
CHUNK_SIZE = 1200
MAX_HISTORY_MESSAGES = 12

# Condensed from CLAUDE.md for local models that can't read the repo themselves.
GUIDE_PERSONA = """\
You are the guide of Second Arrow, a personal study space for learning
Buddhism and working with anger. You are a guide-teacher using real
teachings — not a coding assistant and not a syllabus.

How to respond:
- Angry or upset right now: keep it small — a short grounding practice,
  then ONE teaching drawn from the transcript excerpts below. No lecture.
- Curious, or wanting a story: offer a small tray — one talk or story, one
  plain-language concept, one practical reflection. Not more.
- Back from a talk: discuss it section by section — what landed, what
  confused, what met resistance.

Hard rules:
- Teach only from the transcript excerpts, notes, and memory given below.
  If the source is not there, say so plainly — never paraphrase a specific
  talk from training-data memory. The original audio is the authority.
- Anger is the root cluster (anger, aversion, patience, the two arrows).
- AA, NDEs, psychology, AI parallels are resonance, not doctrine.
- This is study material, not scripture, therapy, or medical advice.
Be warm and brief. Quote the transcripts when you can."""

STOPWORDS = frozenset(
    """a an and are as at be but by do does for from he had has have how i in
    is it its me my of on or she so that the their them they this to was we
    what when where which who why will with you your""".split()
)


class BrainError(Exception):
    """A user-facing brain failure: carries an HTTP status and a plain message."""

    def __init__(self, status: int, message: str):
        super().__init__(message)
        self.status = status
        self.message = message


# --- pure helpers (tested in tools/tests/test_serve_shelf.py) -----------


def chunk_transcript(text: str, size: int = CHUNK_SIZE) -> list[str]:
    """Split text into ~size-char chunks on word boundaries. No empty chunks."""
    chunks: list[str] = []
    current: list[str] = []
    length = 0
    for word in text.split():
        current.append(word)
        length += len(word) + 1
        if length >= size:
            chunks.append(" ".join(current))
            current, length = [], 0
    if current:
        chunks.append(" ".join(current))
    return chunks


def _keywords(text: str) -> set[str]:
    return {
        w
        for w in re.findall(r"[a-z']+", text.lower())
        if len(w) > 2 and w not in STOPWORDS
    }


def pick_chunks(
    question: str, transcripts: dict[str, str], k: int = 4
) -> list[tuple[str, str]]:
    """Top-k transcript chunks by keyword overlap with the question.

    transcripts maps talk title -> full transcript text. Returns
    (title, chunk) pairs, best first; chunks with no overlap are dropped.
    """
    terms = _keywords(question)
    scored: list[tuple[int, str, str]] = []
    for title, text in transcripts.items():
        for chunk in chunk_transcript(text):
            score = len(terms & _keywords(chunk))
            if score:
                scored.append((score, title, chunk))
    scored.sort(key=lambda item: -item[0])  # stable: ties keep shelf order
    return [(title, chunk) for _, title, chunk in scored[:k]]


def build_system_prompt(
    study: str, index: str, chunks: list[tuple[str, str]]
) -> str:
    parts = [GUIDE_PERSONA]
    if study.strip():
        parts.append("## Study memory (STUDY.md)\n\n" + study.strip())
    if index.strip():
        parts.append("## Library index\n\n" + index.strip())
    if chunks:
        excerpts = "\n\n".join(
            f'### From "{title}"\n\n{chunk}' for title, chunk in chunks
        )
        parts.append("## Transcript excerpts (teach from these)\n\n" + excerpts)
    return "\n\n".join(parts)


def build_ollama_payload(
    messages: list[dict],
    model: str,
    study: str = "",
    index: str = "",
    chunks: list[tuple[str, str]] = (),
) -> dict:
    system = build_system_prompt(study, index, list(chunks))
    return {
        "model": model,
        "messages": [{"role": "system", "content": system}, *messages],
        "stream": False,
    }


def build_claude_cmd(prompt: str, session_id: str | None = None) -> list[str]:
    cmd = ["claude", "-p", prompt, "--output-format", "json"]
    if session_id:
        cmd += ["--resume", session_id]
    return cmd


def trim_history(messages: list[dict], max_messages: int = MAX_HISTORY_MESSAGES) -> list[dict]:
    return list(messages[-max_messages:])


def history_prompt(messages: list[dict]) -> str:
    """Fold earlier turns into one prompt (first turn, or resume fallback)."""
    trimmed = trim_history(messages)
    if len(trimmed) == 1:
        return trimmed[0]["content"]
    lines = ["Earlier in this conversation:", ""]
    for message in trimmed[:-1]:
        who = "Student" if message["role"] == "user" else "Guide"
        lines.append(f"{who}: {message['content']}")
    lines += ["", f"Student: {trimmed[-1]['content']}"]
    return "\n".join(lines)


def parse_claude_output(stdout: str) -> tuple[str, str | None]:
    """Pull (reply, session_id) out of `claude --output-format json` stdout.

    Depending on CLI version the JSON is either a single result object or a
    list of events whose last "result"-typed item holds the reply.
    """
    data = json.loads(stdout)
    if isinstance(data, list):
        results = [item for item in data if item.get("type") == "result"]
        if not results:
            raise ValueError("no result event in claude output")
        data = results[-1]
    if data.get("is_error"):
        raise ValueError(str(data.get("result") or "claude reported an error"))
    return (data.get("result") or "").strip(), data.get("session_id")


def strip_think(text: str) -> str:
    """Drop <think>...</think> reasoning blocks some local models emit."""
    return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()


def resolve_ollama_model(configured: str, installed: list[str]) -> str:
    """Use the configured model if installed (tag-insensitive), else the first."""
    for name in installed:
        if name == configured or name.split(":")[0] == configured:
            return name
    return installed[0] if installed else configured


# --- shelf + library ----------------------------------------------------


def load_build_shelf():
    path = Path(__file__).resolve().parent / "build_shelf.py"
    spec = importlib.util.spec_from_file_location("build_shelf", path)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


def rebuild_shelf(library: Path) -> Path:
    build_shelf = load_build_shelf()
    reach = build_shelf.collect_reach(library.parent / "curriculum")
    output = library / "shelf.html"
    output.write_text(build_shelf.render_shelf(library, reach))
    return output


def load_transcripts(library: Path) -> dict[str, str]:
    """Map talk title (from INDEX.md, slug fallback) -> transcript text."""
    build_shelf = load_build_shelf()
    transcripts: dict[str, str] = {}
    for talk in build_shelf.parse_index((library / "INDEX.md").read_text()):
        path = library / talk["slug"] / "transcript.md"
        if path.exists():
            transcripts[talk.get("title", talk["slug"])] = path.read_text()
    return transcripts


# --- the two brains -----------------------------------------------------


def ask_claude(messages: list[dict], state: dict) -> str:
    session_id = state.get("session_id")
    prompt = messages[-1]["content"] if session_id else history_prompt(messages)
    cmd = build_claude_cmd(prompt, session_id)
    try:
        proc = subprocess.run(
            cmd,
            cwd=REPO_ROOT,
            stdin=subprocess.DEVNULL,  # claude -p waits on a dangling stdin pipe
            capture_output=True,
            text=True,
            timeout=CLAUDE_TIMEOUT,
        )
    except FileNotFoundError:
        raise BrainError(503, "The claude CLI is not on PATH — install Claude Code.")
    except subprocess.TimeoutExpired:
        raise BrainError(504, "The guide took too long to answer — try again.")
    if proc.returncode != 0:
        if session_id:  # resume proved flaky: retry fresh with folded history
            state["session_id"] = None
            return ask_claude(messages, state)
        raise BrainError(
            502, f"claude exited with {proc.returncode}: {proc.stderr.strip()[:300]}"
        )
    try:
        reply, new_session = parse_claude_output(proc.stdout)
    except json.JSONDecodeError:
        raise BrainError(502, "claude returned something that was not JSON.")
    except ValueError as error:
        raise BrainError(502, f"claude reported an error: {error}")
    if new_session:
        state["session_id"] = new_session
    if not reply:
        raise BrainError(502, "claude returned an empty reply.")
    return reply


def _ollama_json(path: str, payload: dict | None = None, timeout: int = 240) -> dict:
    request = urllib.request.Request(
        OLLAMA_URL + path,
        data=json.dumps(payload).encode() if payload is not None else None,
        headers={"Content-Type": "application/json"} if payload is not None else {},
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return json.loads(response.read())


def ask_ollama(messages: list[dict], configured_model: str, library: Path) -> str:
    try:
        tags = _ollama_json("/api/tags", timeout=5)
    except (urllib.error.URLError, OSError, TimeoutError):
        raise BrainError(
            503,
            "Ollama is not reachable at localhost:11434 — "
            "run `ollama serve` and try again.",
        )
    installed = [m["name"] for m in tags.get("models", [])]
    if not installed:
        raise BrainError(
            503,
            "Ollama is running but has no models — "
            f"try `ollama pull {configured_model}`.",
        )
    model = resolve_ollama_model(configured_model, installed)
    if model.split(":")[0] != configured_model.split(":")[0]:
        print(f"[serve_shelf] {configured_model!r} not installed; using {model!r}")

    study_path = library.parent / "STUDY.md"
    study = study_path.read_text() if study_path.exists() else ""
    index = (library / "INDEX.md").read_text()
    chunks = pick_chunks(messages[-1]["content"], load_transcripts(library), k=4)
    payload = build_ollama_payload(trim_history(messages), model, study, index, chunks)
    try:
        data = _ollama_json("/api/chat", payload)
    except (urllib.error.URLError, OSError, TimeoutError):
        raise BrainError(
            503,
            "Ollama stopped answering mid-conversation — "
            "check `ollama serve` and try again.",
        )
    reply = strip_think(data.get("message", {}).get("content", ""))
    if not reply:
        raise BrainError(502, f"Ollama ({model}) returned an empty reply.")
    return reply


# --- the server ---------------------------------------------------------


def create_app(brain: str, ollama_model: str):
    from fastapi import FastAPI
    from fastapi.responses import FileResponse, JSONResponse
    from fastapi.staticfiles import StaticFiles

    shelf = rebuild_shelf(LIBRARY)
    print(f"[serve_shelf] rebuilt {shelf}")

    app = FastAPI(title="Second Arrow — Study Shelf")
    state: dict = {"session_id": None}

    @app.get("/")
    def index() -> FileResponse:
        return FileResponse(LIBRARY / "shelf.html", media_type="text/html")

    @app.get("/health")
    def health() -> dict:
        return {"ok": True, "brain": brain}

    @app.post("/api/chat")
    def chat(body: dict):
        messages = body.get("messages")
        if (
            not isinstance(messages, list)
            or not messages
            or not all(
                isinstance(m, dict)
                and m.get("role") in ("user", "assistant")
                and isinstance(m.get("content"), str)
                for m in messages
            )
            or messages[-1]["role"] != "user"
        ):
            return JSONResponse(
                {"error": "Body must be {\"messages\": [...]} ending with a user message."},
                status_code=422,
            )
        try:
            if brain == "claude":
                reply = ask_claude(messages, state)
            else:
                reply = ask_ollama(messages, ollama_model, LIBRARY)
        except BrainError as error:
            return JSONResponse({"error": error.message}, status_code=error.status)
        return {"reply": reply, "brain": brain}

    # Mounted last so /, /health, /api/chat win; everything else — primers,
    # talk audio, transcripts — is served straight from library/ with Range
    # support, matching the shelf's relative srcs.
    app.mount("/", StaticFiles(directory=LIBRARY), name="library")
    return app


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve the study shelf with a guide chat.")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--brain", choices=("claude", "ollama"), default="claude")
    parser.add_argument("--ollama-model", default="qwen3")
    args = parser.parse_args()

    if not (LIBRARY / "INDEX.md").exists():
        raise SystemExit(f"No {LIBRARY / 'INDEX.md'} found — ingest a talk first.")

    import uvicorn

    app = create_app(args.brain, args.ollama_model)
    print(f"[serve_shelf] guide brain: {args.brain}")
    print(f"[serve_shelf] open http://localhost:{args.port}")
    uvicorn.run(app, host="127.0.0.1", port=args.port)


if __name__ == "__main__":
    main()
