#!/usr/bin/env python3
# /// script
# dependencies = ["fastapi", "uvicorn"]
# ///
"""Serve the study shelf with a guide chat panel.

Binds 127.0.0.1 only. On startup the shelf page is regenerated by importing
the sibling build_shelf.py by path (importlib, the same pattern the tests
use) rather than shelling out through `uv run` — build_shelf is stdlib-only,
so importing it is fast, in-process, and fails loudly if it breaks.

Routes:
    GET  /          the shelf page (library/shelf.html, freshly rebuilt)
    GET  /health    {"ok": true, "brain": "claude"|"ollama"}
    POST /api/chat  {"messages": [{"role", "content"}, ...]} -> streamed reply
    /<talk>/...     library/ served statically (Range supported, audio seeks)

Chat replies stream as chunked plain text (`text/plain; charset=utf-8`,
one raw text fragment per chunk — no SSE framing; the panel just appends
each decoded chunk with textContent). Failures BEFORE the stream starts
still return JSON {"error": ...} with a 4xx/5xx status; failures MID-stream
degrade gracefully: whatever text already arrived is kept and one plain
error sentence is appended.

Two brains:
    --brain claude (default)  runs the authenticated Claude CLI headless in
        this repo (`--output-format stream-json --include-partial-messages`),
        so it inherits the CLAUDE.md guide persona and can read library/
        itself. Writes are scoped: `--permission-mode default` plus an
        --allowedTools allowlist grant Edit/Write ONLY on STUDY.md,
        journal/**, library/**/notes.md, and library/INDEX.md — no Bash,
        nothing else. That is the safety boundary (see chat_allowed_tools).
        Conversation continuity via `--resume <session_id>`, falling back
        to folding trimmed history into the prompt.
    --brain ollama  talks to a local Ollama (http://localhost:11434) with
        "stream": true, read-only. Local models are weak rememberers, so the
        server does the remembering: a condensed guide persona + STUDY.md +
        library/INDEX.md + the top keyword-matched transcript chunks are
        packed into the system prompt. <think> blocks are filtered out of
        the stream (ThinkFilter).

Run with:
    uv run tools/serve_shelf.py                # then open http://localhost:8765
    uv run tools/serve_shelf.py --brain ollama --ollama-model qwen3

Tests (fastapi/uvicorn are lazy-imported, so plain pytest can load this file):
    uv run --with pytest pytest tools/tests/test_serve_shelf.py -v
"""

import argparse
import importlib.util
import json
import re
import subprocess
import threading
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LIBRARY = REPO_ROOT / "library"
OLLAMA_URL = "http://localhost:11434"
CLAUDE_TIMEOUT = 240  # seconds — guide turns can take a while
CHUNK_SIZE = 1200
MAX_HISTORY_MESSAGES = 12

# Condensed from CLAUDE.md for local models that can't read the repo themselves.
GUIDE_PERSONA = """\
You are the guide of Second Arrow, a personal study space for learning
Buddhism and working with anger. You are a guide-teacher using real
teachings — not a coding assistant and not a syllabus.

How to respond:
- Angry or upset right now: keep it small — a short grounding practice,
  then ONE teaching drawn from the transcript excerpts below. No lecture.
- Curious, or wanting a story: offer a small tray — one talk or story, one
  plain-language concept, one practical reflection. Not more.
- Back from a talk: discuss it section by section — what landed, what
  confused, what met resistance.

Hard rules:
- Teach only from the transcript excerpts, notes, and memory given below.
  If the source is not there, say so plainly — never paraphrase a specific
  talk from training-data memory. The original audio is the authority.
- Anger is the root cluster (anger, aversion, patience, the two arrows).
- AA, NDEs, psychology, AI parallels are resonance, not doctrine.
- This is study material, not scripture, therapy, or medical advice.
Be warm and brief. Quote the transcripts when you can."""

STOPWORDS = frozenset(
    """a an and are as at be but by do does for from he had has have how i in
    is it its me my of on or she so that the their them they this to was we
    what when where which who why will with you your""".split()
)


class BrainError(Exception):
    """A user-facing brain failure: carries an HTTP status and a plain message."""

    def __init__(self, status: int, message: str):
        super().__init__(message)
        self.status = status
        self.message = message


# --- pure helpers (tested in tools/tests/test_serve_shelf.py) -----------


def chunk_transcript(text: str, size: int = CHUNK_SIZE) -> list[str]:
    """Split text into ~size-char chunks on word boundaries. No empty chunks."""
    chunks: list[str] = []
    current: list[str] = []
    length = 0
    for word in text.split():
        current.append(word)
        length += len(word) + 1
        if length >= size:
            chunks.append(" ".join(current))
            current, length = [], 0
    if current:
        chunks.append(" ".join(current))
    return chunks


def _keywords(text: str) -> set[str]:
    return {
        w
        for w in re.findall(r"[a-z']+", text.lower())
        if len(w) > 2 and w not in STOPWORDS
    }


def pick_chunks(
    question: str, transcripts: dict[str, str], k: int = 4
) -> list[tuple[str, str]]:
    """Top-k transcript chunks by keyword overlap with the question.

    transcripts maps talk title -> full transcript text. Returns
    (title, chunk) pairs, best first; chunks with no overlap are dropped.
    """
    terms = _keywords(question)
    scored: list[tuple[int, str, str]] = []
    for title, text in transcripts.items():
        for chunk in chunk_transcript(text):
            score = len(terms & _keywords(chunk))
            if score:
                scored.append((score, title, chunk))
    scored.sort(key=lambda item: -item[0])  # stable: ties keep shelf order
    return [(title, chunk) for _, title, chunk in scored[:k]]


def build_system_prompt(
    study: str, index: str, chunks: list[tuple[str, str]]
) -> str:
    parts = [GUIDE_PERSONA]
    if study.strip():
        parts.append("## Study memory (STUDY.md)\n\n" + study.strip())
    if index.strip():
        parts.append("## Library index\n\n" + index.strip())
    if chunks:
        excerpts = "\n\n".join(
            f'### From "{title}"\n\n{chunk}' for title, chunk in chunks
        )
        parts.append("## Transcript excerpts (teach from these)\n\n" + excerpts)
    return "\n\n".join(parts)


def build_ollama_payload(
    messages: list[dict],
    model: str,
    study: str = "",
    index: str = "",
    chunks: list[tuple[str, str]] = (),
    stream: bool = False,
) -> dict:
    system = build_system_prompt(study, index, list(chunks))
    return {
        "model": model,
        "messages": [{"role": "system", "content": system}, *messages],
        "stream": stream,
    }


# The chat guide's durable memory: the ONLY paths it may write from chat.
# Everything else (code, curriculum, committed docs) needs a full session.
CHAT_WRITE_SCOPES = (
    "STUDY.md",
    "journal/**",
    "library/**/notes.md",
    "library/INDEX.md",
)


def chat_allowed_tools(scopes: tuple[str, ...] = CHAT_WRITE_SCOPES) -> str:
    """Comma-joined --allowedTools rules: Edit+Write per scope, nothing else.

    Verified against the real CLI: `--allowedTools "Edit(STUDY.md),..."`
    with `--permission-mode default` lets those edits through and leaves
    every other write pending-denied in headless mode. (This CLI version
    has no separate MultiEdit tool — Edit covers multi-edits.)
    """
    return ",".join(
        f"{tool}({scope})" for scope in scopes for tool in ("Edit", "Write")
    )


def build_claude_cmd(prompt: str, session_id: str | None = None) -> list[str]:
    cmd = [
        "claude",
        "-p",
        prompt,
        "--output-format",
        "stream-json",
        "--verbose",  # stream-json in -p mode requires it
        "--include-partial-messages",
        # A user-level defaultMode like "auto" would auto-accept ANY write;
        # pinning "default" makes the allowlist below the whole boundary.
        "--permission-mode",
        "default",
        "--allowedTools",
        chat_allowed_tools(),
    ]
    if session_id:
        cmd += ["--resume", session_id]
    return cmd


def trim_history(messages: list[dict], max_messages: int = MAX_HISTORY_MESSAGES) -> list[dict]:
    return list(messages[-max_messages:])


def history_prompt(messages: list[dict]) -> str:
    """Fold earlier turns into one prompt (first turn, or resume fallback)."""
    trimmed = trim_history(messages)
    if len(trimmed) == 1:
        return trimmed[0]["content"]
    lines = ["Earlier in this conversation:", ""]
    for message in trimmed[:-1]:
        who = "Student" if message["role"] == "user" else "Guide"
        lines.append(f"{who}: {message['content']}")
    lines += ["", f"Student: {trimmed[-1]['content']}"]
    return "\n".join(lines)


def parse_claude_output(stdout: str) -> tuple[str, str | None]:
    """Pull (reply, session_id) out of `claude --output-format json` stdout.

    Depending on CLI version the JSON is either a single result object or a
    list of events whose last "result"-typed item holds the reply. (The
    server itself now streams via parse_stream_line; this is the one-shot
    counterpart, kept for scripts and fallback use.)
    """
    data = json.loads(stdout)
    if isinstance(data, list):
        results = [item for item in data if item.get("type") == "result"]
        if not results:
            raise ValueError("no result event in claude output")
        data = results[-1]
    if data.get("is_error"):
        raise ValueError(str(data.get("result") or "claude reported an error"))
    return (data.get("result") or "").strip(), data.get("session_id")


def parse_stream_line(line: str) -> dict:
    """Parse one line of `claude -p --output-format stream-json` output.

    Returns {"text": str|None, "session_id": str|None, "done": bool}:
    text is a visible reply fragment (only content_block_delta/text_delta —
    thinking and signature deltas stay hidden), session_id rides on most
    events (the system/init event carries it first), done marks the final
    "result" event. Raises json.JSONDecodeError on a garbled line and
    ValueError when the result event reports is_error.
    """
    parsed: dict = {"text": None, "session_id": None, "done": False}
    line = line.strip()
    if not line:
        return parsed
    data = json.loads(line)
    if not isinstance(data, dict):
        return parsed
    session_id = data.get("session_id")
    if isinstance(session_id, str) and session_id:
        parsed["session_id"] = session_id
    if data.get("type") == "stream_event":
        event = data.get("event") or {}
        delta = event.get("delta") or {}
        if (
            event.get("type") == "content_block_delta"
            and delta.get("type") == "text_delta"
        ):
            parsed["text"] = delta.get("text") or None
    elif data.get("type") == "result":
        if data.get("is_error"):
            raise ValueError(str(data.get("result") or "claude reported an error"))
        parsed["done"] = True
    return parsed


def parse_ollama_stream_line(line: str) -> dict:
    """Parse one NDJSON line from Ollama /api/chat with "stream": true.

    Returns {"text": str|None, "done": bool}. Raises json.JSONDecodeError
    on a garbled line and ValueError when Ollama reports an error.
    """
    line = line.strip()
    if not line:
        return {"text": None, "done": False}
    data = json.loads(line)
    if data.get("error"):
        raise ValueError(str(data["error"]))
    text = data.get("message", {}).get("content") or None
    return {"text": text, "done": bool(data.get("done"))}


def strip_think(text: str) -> str:
    """Drop <think>...</think> reasoning blocks some local models emit.

    One-shot counterpart of ThinkFilter (which handles streamed chunks).
    """
    return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()


def _partial_tag_suffix(text: str, tag: str) -> int:
    """Length of the longest suffix of text that is a proper prefix of tag."""
    for size in range(min(len(tag) - 1, len(text)), 0, -1):
        if tag.startswith(text[-size:]):
            return size
    return 0


class ThinkFilter:
    """strip_think for streams: drop <think>...</think> across chunk edges.

    feed() returns the visible part of each chunk, holding back any tail
    that might be the start of a split tag; flush() releases a held false
    alarm once the stream ends. Leading whitespace before the first visible
    text is swallowed so the bubble doesn't open with blank lines.
    """

    OPEN = "<think>"
    CLOSE = "</think>"

    def __init__(self) -> None:
        self._pending = ""
        self._in_think = False
        self._started = False

    def _emit(self, visible: str) -> str:
        if not self._started:
            visible = visible.lstrip()
        if visible:
            self._started = True
        return visible

    def feed(self, chunk: str) -> str:
        text = self._pending + chunk
        self._pending = ""
        out: list[str] = []
        while text:
            tag = self.CLOSE if self._in_think else self.OPEN
            index = text.find(tag)
            if index == -1:
                keep = _partial_tag_suffix(text, tag)
                if keep:
                    self._pending = text[-keep:]
                    text = text[:-keep]
                if not self._in_think:
                    out.append(text)
                text = ""
            elif self._in_think:
                self._in_think = False
                text = text[index + len(tag) :]
            else:
                out.append(text[:index])
                self._in_think = True
                text = text[index + len(tag) :]
        return self._emit("".join(out))

    def flush(self) -> str:
        visible = "" if self._in_think else self._pending
        self._pending = ""
        return self._emit(visible)


def resolve_ollama_model(configured: str, installed: list[str]) -> str:
    """Use the configured model if installed (tag-insensitive), else the first."""
    for name in installed:
        if name == configured or name.split(":")[0] == configured:
            return name
    return installed[0] if installed else configured


# --- shelf + library ----------------------------------------------------


def load_build_shelf():
    path = Path(__file__).resolve().parent / "build_shelf.py"
    spec = importlib.util.spec_from_file_location("build_shelf", path)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


def rebuild_shelf(library: Path) -> Path:
    build_shelf = load_build_shelf()
    reach = build_shelf.collect_reach(library.parent / "curriculum")
    output = library / "shelf.html"
    output.write_text(build_shelf.render_shelf(library, reach))
    return output


def load_transcripts(library: Path) -> dict[str, str]:
    """Map talk title (from INDEX.md, slug fallback) -> transcript text."""
    build_shelf = load_build_shelf()
    transcripts: dict[str, str] = {}
    for talk in build_shelf.parse_index((library / "INDEX.md").read_text()):
        path = library / talk["slug"] / "transcript.md"
        if path.exists():
            transcripts[talk.get("title", talk["slug"])] = path.read_text()
    return transcripts


# --- the two brains (both stream) ----------------------------------------

STREAM_BROKE = "the stream broke off here. Ask again and I'll pick it back up."


def _spawn_claude(prompt: str, session_id: str | None) -> subprocess.Popen:
    try:
        return subprocess.Popen(
            build_claude_cmd(prompt, session_id),
            cwd=REPO_ROOT,
            stdin=subprocess.DEVNULL,  # claude -p waits on a dangling stdin pipe
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            bufsize=1,  # line-buffered: one stream-json event per readline
        )
    except FileNotFoundError:
        raise BrainError(503, "The claude CLI is not on PATH — install Claude Code.")


def _drain_claude(proc: subprocess.Popen, state: dict):
    """Yield text deltas from a running claude stream-json process.

    Generator-returns (emitted_any_text, finished_cleanly). A single
    garbled line is skipped; an is_error result or a bad exit just flips
    the flag — the caller decides how to apologise.
    """
    emitted, finished = False, False
    watchdog = threading.Timer(CLAUDE_TIMEOUT, proc.kill)
    watchdog.start()
    try:
        assert proc.stdout is not None
        for line in proc.stdout:
            try:
                event = parse_stream_line(line)
            except json.JSONDecodeError:
                continue  # one garbled line shouldn't sink the reply
            except ValueError:
                break  # the CLI reported an error result
            if event["session_id"]:
                state["session_id"] = event["session_id"]
            if event["text"]:
                emitted = True
                yield event["text"]
            if event["done"]:
                finished = True
        proc.wait(timeout=10)
    except (OSError, subprocess.TimeoutExpired):
        pass
    finally:
        watchdog.cancel()
        if proc.poll() is None:
            proc.kill()
            proc.wait()
    return emitted, finished and proc.returncode == 0


def stream_claude(messages: list[dict], state: dict):
    """Start a claude turn; return a generator of reply-text chunks.

    Raises BrainError before any output if the CLI can't even start.
    Mid-stream failures degrade gracefully: a resume that dies before
    producing text is retried fresh with folded history (resume has proved
    flaky); anything else keeps what arrived and appends one apology.
    """
    session_id = state.get("session_id")
    prompt = messages[-1]["content"] if session_id else history_prompt(messages)
    proc = _spawn_claude(prompt, session_id)

    def generate():
        emitted, ok = yield from _drain_claude(proc, state)
        if not ok and not emitted and session_id:
            state["session_id"] = None  # retry fresh with folded history
            try:
                retry = _spawn_claude(history_prompt(messages), None)
            except BrainError as error:
                yield f"The guide is out of reach — {error.message}"
                return
            emitted, ok = yield from _drain_claude(retry, state)
        if not ok:
            yield ("\n\n— " if emitted else "The guide is out of reach — ") + STREAM_BROKE
        elif not emitted:
            yield "The guide said nothing this time — try asking again."

    return generate()


def _ollama_json(path: str, payload: dict | None = None, timeout: int = 240) -> dict:
    request = urllib.request.Request(
        OLLAMA_URL + path,
        data=json.dumps(payload).encode() if payload is not None else None,
        headers={"Content-Type": "application/json"} if payload is not None else {},
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return json.loads(response.read())


def stream_ollama(messages: list[dict], configured_model: str, library: Path):
    """Start an Ollama turn; return a generator of reply-text chunks.

    Pre-flight (reachability, model resolution, opening the streamed POST)
    raises BrainError so the endpoint can still answer with a proper JSON
    error; once streaming, failures keep what arrived plus one apology.
    <think> blocks are filtered out on the way through (ThinkFilter).
    """
    try:
        tags = _ollama_json("/api/tags", timeout=5)
    except (urllib.error.URLError, OSError, TimeoutError):
        raise BrainError(
            503,
            "Ollama is not reachable at localhost:11434 — "
            "run `ollama serve` and try again.",
        )
    installed = [m["name"] for m in tags.get("models", [])]
    if not installed:
        raise BrainError(
            503,
            "Ollama is running but has no models — "
            f"try `ollama pull {configured_model}`.",
        )
    model = resolve_ollama_model(configured_model, installed)
    if model.split(":")[0] != configured_model.split(":")[0]:
        print(f"[serve_shelf] {configured_model!r} not installed; using {model!r}")

    study_path = library.parent / "STUDY.md"
    study = study_path.read_text() if study_path.exists() else ""
    index = (library / "INDEX.md").read_text()
    chunks = pick_chunks(messages[-1]["content"], load_transcripts(library), k=4)
    payload = build_ollama_payload(
        trim_history(messages), model, study, index, chunks, stream=True
    )
    request = urllib.request.Request(
        OLLAMA_URL + "/api/chat",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"},
    )
    try:  # urlopen returns once headers arrive; the body then streams NDJSON
        response = urllib.request.urlopen(request, timeout=120)
    except (urllib.error.URLError, OSError, TimeoutError):
        raise BrainError(
            503,
            "Ollama stopped answering mid-conversation — "
            "check `ollama serve` and try again.",
        )

    def generate():
        think = ThinkFilter()
        emitted = False
        try:
            with response:
                for raw in response:  # one NDJSON object per line
                    parsed = parse_ollama_stream_line(raw.decode("utf-8", "replace"))
                    if parsed["text"]:
                        visible = think.feed(parsed["text"])
                        if visible:
                            emitted = True
                            yield visible
                    if parsed["done"]:
                        break
            tail = think.flush()
            if tail:
                emitted = True
                yield tail
            if not emitted:
                yield f"Ollama ({model}) returned an empty reply — try again."
        except (json.JSONDecodeError, ValueError, urllib.error.URLError, OSError, TimeoutError):
            yield ("\n\n— " if emitted else "The guide is out of reach — ") + STREAM_BROKE

    return generate()


# --- the server ---------------------------------------------------------


def create_app(brain: str, ollama_model: str):
    from fastapi import FastAPI
    from fastapi.responses import FileResponse, JSONResponse, StreamingResponse
    from fastapi.staticfiles import StaticFiles

    shelf = rebuild_shelf(LIBRARY)
    print(f"[serve_shelf] rebuilt {shelf}")

    app = FastAPI(title="Second Arrow — Study Shelf")
    state: dict = {"session_id": None}

    @app.get("/")
    def index() -> FileResponse:
        return FileResponse(LIBRARY / "shelf.html", media_type="text/html")

    @app.get("/health")
    def health() -> dict:
        return {"ok": True, "brain": brain}

    @app.post("/api/chat")
    def chat(body: dict):
        messages = body.get("messages")
        if (
            not isinstance(messages, list)
            or not messages
            or not all(
                isinstance(m, dict)
                and m.get("role") in ("user", "assistant")
                and isinstance(m.get("content"), str)
                for m in messages
            )
            or messages[-1]["role"] != "user"
        ):
            return JSONResponse(
                {"error": "Body must be {\"messages\": [...]} ending with a user message."},
                status_code=422,
            )
        try:
            if brain == "claude":
                stream = stream_claude(messages, state)
            else:
                stream = stream_ollama(messages, ollama_model, LIBRARY)
        except BrainError as error:
            return JSONResponse({"error": error.message}, status_code=error.status)
        # Chunked plain text: each chunk is a raw reply fragment (no framing).
        return StreamingResponse(
            stream,
            media_type="text/plain; charset=utf-8",
            headers={"X-Brain": brain},
        )

    # Mounted last so /, /health, /api/chat win; everything else — primers,
    # talk audio, transcripts — is served straight from library/ with Range
    # support, matching the shelf's relative srcs.
    app.mount("/", StaticFiles(directory=LIBRARY), name="library")
    return app


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve the study shelf with a guide chat.")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--brain", choices=("claude", "ollama"), default="claude")
    parser.add_argument("--ollama-model", default="qwen3")
    args = parser.parse_args()

    if not (LIBRARY / "INDEX.md").exists():
        raise SystemExit(f"No {LIBRARY / 'INDEX.md'} found — ingest a talk first.")

    import uvicorn

    app = create_app(args.brain, args.ollama_model)
    print(f"[serve_shelf] guide brain: {args.brain}")
    print(f"[serve_shelf] open http://localhost:{args.port}")
    uvicorn.run(app, host="127.0.0.1", port=args.port)


if __name__ == "__main__":
    main()
